[tjs]

[tjs.rj]
code = 19
cnj_endpoint = "https://www3.tjrj.jus.br/consultaprocessual/api/processos/por-numeracao-unica"
main_endpoint = "https://www3.tjrj.jus.br/consultaprocessual/api/processos/por-numero/publica"
source_units= [  # From: https://www.tjrj.jus.br/consultas/cod_serventias/cons_cod_serventias
    { code = 0, name = "Processos de 2ª Instância" },
    { code = 1, name = "Comarca da Capital" },
    # { code = 1, name = "Processos da VEP" },
    { code = 10, name = "Comarca de Bom Jesus de Itabapoana" },
    { code = 11, name = "Comarca de Cabo Frio" },
    { code = 12, name = "Comarca de Cachoeiras de Macacu" },
    { code = 13, name = "Comarca de Cambuci" },
    { code = 14, name = "Comarca de Campos dos Goytacazes" },
    { code = 15, name = "Comarca de Cantagalo" },
    { code = 16, name = "Comarca de Carmo" },
    { code = 17, name = "Comarca de Casimiro de Abreu" },
    { code = 18, name = "Comarca de Conceição de Macabu" },
    { code = 19, name = "Comarca de Cordeiro" },
    { code = 2, name = "Comarca de Niterói" },
    { code = 20, name = "Comarca de Duas Barras" },
    { code = 202, name = "Regional de Madureira" },
    { code = 203, name = "Regional de Jacarepaguá" },
    { code = 204, name = "Regional de Bangu" },
    { code = 205, name = "Regional de Campo Grande" },
    { code = 206, name = "Regional de Santa Cruz" },
    { code = 207, name = "Regional da Ilha do Governador" },
    { code = 208, name = "Regional do Méier" },
    { code = 209, name = "Regional da Barra da Tijuca" },
    { code = 21, name = "Comarca de Duque de Caxias" },
    { code = 210, name = "Regional da Leopoldina" },
    { code = 211, name = "Regional da Pavuna" },
    { code = 212, name = "Regional da Região Oceânica" },
    { code = 22, name = "Comarca de Engenheiro Paulo de Frontin" },
    { code = 23, name = "Comarca de Itaboraí" },
    { code = 24, name = "Comarca de Itaguaí" },
    { code = 25, name = "Comarca de Itaocara" },
    { code = 26, name = "Comarca de Itaperuna" },
    { code = 27, name = "Comarca de Laje do Muriaé" },
    { code = 28, name = "Comarca de Macaé" },
    { code = 29, name = "Comarca de Magé" },
    { code = 3, name = "Comarca de Angra dos Reis" },
    { code = 30, name = "Comarca de Mangaratiba" },
    { code = 31, name = "Comarca de Maricá" },
    { code = 32, name = "Comarca de Mendes" },
    { code = 33, name = "Comarca de Miguel Pereira" },
    { code = 34, name = "Comarca de Miracema" },
    { code = 35, name = "Comarca de Natividade" },
    { code = 36, name = "Comarca de Nilópolis" },
    { code = 37, name = "Comarca de Nova Friburgo" },
    { code = 38, name = "Comarca de Nova Iguaçu" },
    { code = 39, name = "Comarca de Paracambi" },
    { code = 4, name = "Comarca de São Gonçalo" },
    { code = 40, name = "Comarca de Paraíba do Sul" },
    { code = 41, name = "Comarca de Paraty" },
    { code = 42, name = "Comarca de Petrópolis" },
    { code = 43, name = "Comarca de Piraí" },
    { code = 44, name = "Comarca de Porciúncula" },
    { code = 45, name = "Comarca de Resende" },
    { code = 46, name = "Comarca de Rio Bonito" },
    { code = 47, name = "Comarca de Rio Claro" },
    { code = 48, name = "Comarca de Rio das Flores" },
    { code = 49, name = "Comarca de Santa Maria Madalena" },
    { code = 5, name = "Comarca de Arraial do Cabo" },
    { code = 50, name = "Comarca de Santo Antônio de Pádua" },
    { code = 51, name = "Comarca de São Fidelis" },
    { code = 52, name = "Comarca de Araruama" },
    { code = 53, name = "Comarca de São João da Barra" },
    { code = 54, name = "Comarca de São João de Meriti" },
    { code = 55, name = "Comarca de São Pedro da Aldeia" },
    { code = 56, name = "Comarca de São Sebastião do Alto" },
    { code = 57, name = "Comarca de Sapucaia" },
    { code = 58, name = "Comarca de Saquarema" },
    { code = 59, name = "Comarca de Silva Jardim" },
    { code = 6, name = "Comarca de Barra do Piraí" },
    { code = 60, name = "Comarca de Sumidouro" },
    { code = 61, name = "Comarca de Teresópolis" },
    { code = 62, name = "Comarca de Trajano de Moraes" },
    { code = 63, name = "Comarca de Três Rios" },
    { code = 64, name = "Comarca de Valença" },
    { code = 65, name = "Comarca de Vassouras" },
    { code = 66, name = "Comarca de Volta Redonda" },
    { code = 67, name = "Comarca de Queimados" },
    { code = 68, name = "Comarca de Rio das Ostras" },
    { code = 69, name = "Comarca de Iguaba Grande" },
    { code = 7, name = "Comarca de Barra Mansa" },
    { code = 70, name = "Comarca de São Francisco do Itabapoana" },
    { code = 71, name = "Comarca de Porto Real - Quatis" },
    { code = 72, name = "Comarca de Paty do Alferes" },
    { code = 73, name = "Comarca de Guapimirim" },
    { code = 75, name = "Comarca de Magé - Regional de Inhomirim" },
    { code = 76, name = "Comarca de São José do Vale do Rio Preto" },
    { code = 77, name = "Comarca de Seropédica" },
    { code = 78, name = "Comarca de Búzios" },
    { code = 79, name = "Regional de Itaipava" },
    { code = 8, name = "Comarca de Belford Roxo" },
    { code = 80, name = "Comarca de Italva" },
    { code = 81, name = "Comarca de Itatiaia" },
    { code = 82, name = "Comarca de Pinheiral" },
    { code = 83, name = "Comarca de Japeri" },
    { code = 84, name = "RComarca de Carapebus / Quissamã" },
    { code = 87, name = "Regional de Alcântara" },
    { code = 9, name = "Comarca de Bom Jardim" },
    { code = 9000, name = "Processos das Turmas Recursais" },
],
