repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy --ignore-missing-imports
        language: system
        types: [python]
      - id: black
        name: black
        entry: poetry run black --check --diff --target-version py310
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
