repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: poetry run summon lint
        language: system
        types: [python]
      - id: format
        name: Format
        entry: poetry run summon format --check
        language: system
        types: [python]
