name: Full check

on: [push]

jobs:
  full-check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install poetry
        run: pip install --user poetry
      - name: Install dependencies
        run: poetry install
      - name: Mypy
        run: poetry run mypy --ignore-missing-imports
      - name: Black
        run: poetry run black --check --diff
      - name: Pylint
        run: poetry run pylint
      - name: Tests
        run: poetry run pytest
