name: Full check

on: [push]

jobs:
  full-check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python 3.10.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install poetry
        run: pip install --user poetry
      - name: Install dependencies
        run: poetry install -E webapp
      - name: Mypy
        if: always()
        run: poetry run mypy --ignore-missing-imports .
      - name: Black
        if: always()
        run: poetry run black --check --diff . --target-version py310
      - name: Pylint
        if: always()
        run: |
          poetry run pylint tj_scraper
          poetry run pylint tests
      - name: Tests
        if: always()
        run: poetry run pytest
